name = "seismic"
uuid = "4c880bc8-450f-4926-bad2-3fe51599cecd"
authors = ["Haakon Ludvig Langeland Ervik <45243236+haakon-e@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
